apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-sdb
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.37.202
    path: /mnt/nfs
