apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-share-normal
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.37.202
    path: /hdd/2

