apiVersion: apps/v1
- hosts: ubuntu
  pre_tasks:
  - name: Prepare. Install packages
    apt:
      name: "curl"
      state: latest
      update_cache: yes
  tasks:
  - name: Add MariaDB repos
    shell: |
      curl -LsS -O https://downloads.mariadb.com/MariaDB/mariadb_repo_setup
      bash mariadb_repo_setup --mariadb-server-version=10.6
  - name: MySQL. Install packages
    apt:
      name: "{{ .Values.app_packages }}"
      state: latest
      update_cache: yes
    environment:
      DEBIAN_FRONTEND: noninteractive
  - name: MySQL. add bind-address
    ini_file:
      dest: /etc/mysql/my.cnf
      section: mysqld
      option: "bind-address"
      value: "{{ ansible_host }}"

  - name: restart mysql if necessary
    command: service mysql restart

#  - mysql_db:
#      name: "{{ .Values.Mysql.db_name }}"
#      state: absent
#      login_unix_socket: /var/run/mysqld/mysqld.sock

  - mysql_db:
      name: "{{ .Values.Mysql.db_name }}"
      encoding: utf8
      login_unix_socket: /var/run/mysqld/mysqld.sock

  - mysql_user:
      name: "{{ .Values.Mysql.db_user }}"
      host: "%"
      password: "{{ .Values.Mysql.db_pass }}"
      priv: "{{ .Values.Mysql.db_name }}.*:ALL"
      login_unix_socket: /var/run/mysqld/mysqld.sock
    no_log: yes

  - mysql_db:
      name: "{{ db2_name }}"
      encoding: utf8
      login_unix_socket: /var/run/mysqld/mysqld.sock

  - mysql_user:
      name: "{{ db2_user }}"
      host: "%"
      password: "{{ db2_pass }}"
      priv: "{{ db2_name }}.*:ALL"
      login_unix_socket: /var/run/mysqld/mysqld.sock
    no_log: yes

  - mysql_db:
      name: "{{ db3_name }}"
      encoding: utf8
      login_unix_socket: /var/run/mysqld/mysqld.sock

  - mysql_user:
      name: "{{ db3_user }}"
      host: "%"
      password: "{{ db3_pass }}"
      priv: "{{ db3_name }}.*:ALL"
      login_unix_socket: /var/run/mysqld/mysqld.sock
    no_log: yes
