all:
  vars:
    ansible_user: root
    ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q jump_sa@178.124.206.53"'
  hosts:
    node1:
      ansible_host: 192.168.203.20
      ip: 192.168.203.20
      access_ip: 192.168.203.20
    node2:
      ansible_host: 192.168.203.19
      ip: 192.168.203.19
      access_ip: 192.168.203.19
  children:
    kube_control_plane:
      hosts:
        node1:
    kube_node:
      hosts:
        node1:
        node2:
    etcd:
      hosts:
        node1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
