
Vagrant.configure("2") do |config|
 config.vm.define "host1" do |debian|
  debian.vm.box = "generic/debian11"
    debian.vm.provider "hyperv" do |hv|
       vb.gui = false
       vb.memory = "1300"
       vb.cpus = "2"
    end
  debian.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -yqq ansible
      ssh-keygen -t rsa
    SHELL
  end
end
