apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-sdb
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  nfs:
    server: 192.168.37.202
    path: /mnt/nfs
