name: Check remote host and push report

on:
  push:
    branches:
    - master

jobs:
  prepare:
    runs-on: ubuntu-latest
    runs-on: self-hosted
    steps:
      - name: Install wget
        run: sudo apt update && sudo apt install -y wget
      - run: echo "wget has been installed"
      - name: Count tabs in file
#        run: name_file=https://raw.githubusercontent.com/Luchik51/homework/master/.github/workflows/first.yaml
#      - run: echo "Count of tabs in file $name_file:" > wget_report.log
        run: |
          name_file=https://raw.githubusercontent.com/Luchik51/homework/master/.github/workflows/first.yaml
          echo "Count of tabs in file $name_file:" > wget_report.log
          wget $name_file
          < first.yaml sed 's/[^\t]//g' | wc -c >> wget_report.log 2>&1
          ls -la
      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          path: wget_report.log
