name: Check remote host and push report

on:
  push:
    branches:
    - master

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Install wget
        run: sudo apt update && sudo apt install -y wget
      - run: echo "wget has been installed"
      - run: |
          < .github/workflows/first.yaml sed 's/[^\t]//g' | wc -c > wget_report.log 2>&1
          ls -la
      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          path: wget_report.log
