---
- name: Nginx. Install packages
  yum:
    name: "{{ yum_http_packages }}"
    state: present
  tags:
  - tests

- name: Nginx. Enable and start service
  service:
    name: nginx
    state: started
    enabled: yes

- name: Ngixn. Enable firewall port
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
    immediate: yes
  with_items:
    - "80/tcp"
    - "443/tcp"
  notify:
    - HTTPD. reload service firewalld
  tags:
  - tests
